name: 'Bump and Push Version'
description: 'Bumps package version, commits, and pushes with retry logic'

inputs:
  package-directory:
    description: 'Directory path to the package (e.g., packages/ts-crossplatform)'
    required: true
  package-name:
    description: 'Package name for commit message (e.g., @jsfsi-core/ts-crossplatform)'
    required: true
  branch:
    description: 'Branch to fetch and push to (default: main)'
    required: false
    default: 'main'
  max-retries:
    description: 'Maximum number of push retries (default: 10)'
    required: false
    default: '10'
  retry-delay:
    description: 'Initial retry delay in seconds (default: 5)'
    required: false
    default: '5'

outputs:
  version:
    description: 'The new version number'
    value: ''

runs:
  using: 'composite'
  steps:
    - name: Fetch latest changes
      shell: bash
      run: |
        git fetch origin ${{ inputs.branch }}
        git pull --rebase origin ${{ inputs.branch }} || true

    - name: Install jq
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Bump patch version
      id: bump
      shell: bash
      working-directory: ${{ inputs.package-directory }}
      run: |
        current=$(jq -r '.version' package.json)
        IFS='.' read -r major minor patch <<< "$current"
        new_version="$major.$minor.$((patch + 1))"

        # Apply version bump
        jq --arg v "$new_version" '.version = $v' package.json > package.tmp && mv package.tmp package.json

        echo "version=$new_version" >> $GITHUB_OUTPUT

    - name: Get new version
      id: version-step
      shell: bash
      working-directory: ${{ inputs.package-directory }}
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Commit version bump
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{ inputs.package-directory }}/package.json
        git commit -m "Bump ${{ inputs.package-name }} to version ${{ steps.version-step.outputs.version }} [skip ci]"

    - name: Push version bump with retry
      shell: bash
      run: |
        MAX_RETRIES=${{ inputs.max-retries }}
        RETRY_DELAY=${{ inputs.retry-delay }}
        ATTEMPT=0

        while [ $ATTEMPT -lt $MAX_RETRIES ]; do
          if git push; then
            echo "Push succeeded"
            exit 0
          fi

          ATTEMPT=$((ATTEMPT + 1))
          if [ $ATTEMPT -lt $MAX_RETRIES ]; then
            echo "Push failed, fetching latest changes and retrying (attempt $ATTEMPT/$MAX_RETRIES)..."
            sleep $RETRY_DELAY
            git pull --rebase origin ${{ inputs.branch }} || true
            RETRY_DELAY=$((RETRY_DELAY * 2))
          else
            echo "Push failed after $MAX_RETRIES attempts"
            exit 1
          fi
        done
